### ISSUE TITLE
Any way to access constants exports?

### ISSUE THREAD

**Issue by vorg** [donmccurdy/KTX-Parse#2]
I'm trying to use ktx-parse when reading gltf files together with basis. It seems that constants enumns like `KTX2SupercompressionScheme` leaving me with parsed file container values like `supercompressionScheme` for guessing. Is that because they are part of KTX2 spec and therefore "known"? 

It would be super handy if i could

```javascript
const { read, write, KTX2SupercompressionScheme } = require('ktx-parse');

...

if (parsedKtx.supercompressionScheme == KTX2SupercompressionScheme.BASISLZ) {
}
```

**Comment by donmccurdy** [comment]
That would be a good change I agree, but they aren't exported at the moment... Are you using JavaScript or TypeScript, out of curiosity?

**Comment by vorg** [comment]
JavaScript

**Comment by donmccurdy** [comment]
Exported all the enums currently in the package with v0.1.0, but not necessarily everything in the KTX specification. Feel free to add what you need to `enums.ts`. :)
